[package]
name = "wget_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.24", features = ["blocking"] }
tokio = { version = "1.48.0", features = ["full"] }
openssl = {version = "0.10", features=["vendored"]}
