[package]
name = "basic_file_server"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "0.8", features = ["os-poll", "net"] }
bytes = "1.5"
md5 = "0.8.0"
clap = { version = "4.2", features = ["derive"] }
async-std = { version = "1.12", features = ["attributes"] }